language: java

jdk:
  - oraclejdk8

sudo:
  false

install:
  ./gradlew assemble

script:
  ./gradlew -Dpastebin4j.devkey=$PASTEBIN_DEV_KEY -Dpastebin4j.username=$PASTEBIN_USERNAME -Dpastebin4j.password=$PASTEBIN_PASSWORD clean check jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)